"""Created routes for projects and logic for retrieving and creating projects

Revision ID: 81561951e13e
Revises: a6c5c7260652
Create Date: 2026-05-27 04:46:15.451796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81561951e13e'
down_revision: Union[str, Sequence[str], None] = 'a6c5c7260652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'published_at')
    # ### end Alembic commands ###
