"""Added content_json field in Project model of JSONB type

Revision ID: a6c5c7260652
Revises: e76c56f52946
Create Date: 2026-05-27 02:25:25.424724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6c5c7260652'
down_revision: Union[str, Sequence[str], None] = 'e76c56f52946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_column('projects', 'content_json')
    # ### end Alembic commands ###
